version: "3"
services:
  edison-client-dev:
    container_name: edison-client-dev
    image: v3n0mhkr/edison-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    working_dir: /app
    env_file:
      - ./client/.env
    networks:
      - edison-dev
    ports:
      - 4173:4173
    volumes:
      - ./client:/app
      - /app/node_modules
      

  edison-server-dev:
    container_name: edison-server-dev
    image: v3n0mhkr/edison-server-dev
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    networks:
      - edison-dev
    ports:
      - 8000:8000
    volumes:
      - ./server:/app


networks:
  edison-dev:
    name: edison-dev
    external: false