name: ci-client

# This workflow will trigger on pull request master

on:
  pull_request: 
    branches: 
      - master
    paths: 
      - client/**

jobs:
  client_ci:
    name: CI Client
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
      - name: Setup env
        uses: alekangelov/secret-envfile@v1
        with:
          content: ${{ secrets.CLIENT_ENVFILE_DEV }}
          filename: client/.env
      - name: Install Deps
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
